### ISSUE TITLE
html organization

### ISSUE THREAD

**Issue by rimmesbe** [saradyson/prj-rev-bwfs-dasmoto#1]
Notice how your html is just one giant block of code. Very difficult to read and understand what is going on. There are different techniques for organizing html so it is much more understandable. In this case we should split the html up into sections using divs. Wrap these lines in a div, and move the id to the div instead of the h2.
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/29979262-cf2dcc92-8f12-11e7-97bb-627cf679b480.png">

https://github.com/saradyson/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L10-L14

**Comment by saradyson** [comment]
Thank you for the feedback!
