### ISSUE TITLE
good use of class

### ISSUE THREAD

**Issue by rimmesbe** [saradyson/prj-rev-bwfs-dasmoto#5]
This is a good class, with a good name. You could replace the span with a `<strong>` tag to get the bold font default and add some semantic value to the font text.

https://github.com/saradyson/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/styles.css#L33-L35

**Comment by saradyson** [comment]
Hi Ryan,

I understand what semantic elements are, but not sure I understand the reference in this particular example. Why would a semantic value be needed if using <strong> instead of a class?

Regards,

Sara

**Comment by rimmesbe** [comment]
"Strong" would mean give this section high value. Price of something is usually an important piece of information, and bold usually means look here. So whatever you wrap in strong tags is important information.

**Comment by saradyson** [comment]
Okay, thank you for the information!
