### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [saradyson/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on the project, it's looking good. You used some good techniques here, I like the efficiency in the css. I created a few issues you should take a look at and implement the changes. Moving into the next sections it is going to be important to compartmentalize the html into manageable sections and components, usually with divs. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by saradyson** [comment]
Thank you for the feedback, Ryan!
